### ISSUE TITLE
Filter operator Tequila & doesn't work

### ISSUE THREAD

**Issue by GregLeBarbar** [epfl-si/accounts-tequila-example#7]
It's possible to use filter operator |  
e.g. `group=idev-fsd-membres|epfl-dojo`

But not filter operator &
e.g. `group=idev-fsd-membres&epfl-dojo`

```
Tequila.start({
    ...
    request: ['uniqueid', 'email', 'group'],
    require: ['group=idev-fsd-membres&epfl-dojo'],
   ...
```

To be checked with CFR

**Comment by GregLeBarbar** [comment]
It seems work like this require: ['group=idev-fsd-membres&group=epfl-dojo'],

**Comment by ponsfrilus** [comment]
It should be `group=groupA&group=groupB`
Also test if the | works if user is not in groupA ..

**Comment by ponsfrilus** [comment]
Just checked :
* AND: `group=groupA&group=groupB`
* OR: `group=groupA|group=groupB`

Note that `group=groupA|groupB`  works only for groupA !

Also, mixing up things is ok, e.g. `(group=epfl-dojo|group=idev-fsd-membres)&(username=userA)` is fine.
